
# Loop constraints
directive set /edge_detect/core/core:rlp CSTEPS_FROM {{. == 0}}
directive set /edge_detect/core/core:rlp/main CSTEPS_FROM {{. == 2} {.. == 0}}

# IO operation constraints
directive set /edge_detect/core/core:rlp/main/FRAME:io_read(vin:rsc.d) CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:io_write(vout:rsc.d) CSTEPS_FROM {{.. == 1}}

# Real operation constraints
directive set /edge_detect/core/core:rlp/main/SHIFT:and CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#2 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#3 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#4 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#5 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#6 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#6 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#7 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#8 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#10 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#9 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#10 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#11 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC4:mux CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC4:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC4:mux#13 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC4:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC4:mux#14 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC4:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC4:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC4:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/abs#3:else:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/abs#3:mux CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/abs#4:else:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/abs#4:mux CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/abs#5:else:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/abs#5:mux CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:if#6:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:mux CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#14 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:if#8:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:mux#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#15 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:if#10:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:mux#2 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#16 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:if#14:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:or#5 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:if#16:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:or#6 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:intensity:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:if#12:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:or#4 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:intensity:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:intensity:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:intensity:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:intensity:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:intensity:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/acc#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:intensity:acc#8 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/acc#2 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:intensity:acc#12 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:intensity:acc#17 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:intensity:acc#14 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:intensity:acc#16 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:intensity:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:intensity:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:intensity:acc#11 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:intensity:acc#13 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:intensity:acc#15 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:intensity:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:or CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:or#3 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC2:mux CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC2:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC2:mux#43 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC2:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC2:mux#44 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC2:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC2:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if:acc#17 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if:acc#18 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if:acc#8 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if#1:acc#11 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if#1:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if#1:acc#12 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if#1:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if#1:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if#1:acc#8 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if#2:acc#17 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if#2:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if#2:acc#18 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if#2:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if#2:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if#2:acc#8 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC2:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/abs:else:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/abs:mux CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/abs#1:else:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/abs#1:mux CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/abs#2:else:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/abs#2:mux CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:if:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:if#2:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:if#4:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC2:and CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if:acc#32 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if:acc#33 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if:acc#34 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if:acc#35 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if:acc#36 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if:acc#37 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if:acc#38 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if:acc#39 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if#2:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if#2:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if#2:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if#2:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if#2:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if#2:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if#2:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if#2:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if#2:acc#8 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:and#3 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:and#4 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:and#5 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:and#6 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:and#7 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:and#8 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:and#9 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:and#10 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:and#11 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:and#12 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:and#13 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:if:else:else:else:mux CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#16 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#20 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#21 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#22 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#11 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#12 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#13 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#14 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#15 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#16 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#2 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#3 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#4 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#5 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#44 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#22 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#47 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#23 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#50 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#24 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#6 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#7 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#8 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#21 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#60 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#17 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#9 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#10 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#18 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#19 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#20 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC2:mux#41 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:mux#55 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#69 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:mux#56 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#70 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#71 CSTEPS_FROM {{.. == 1}}
