// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2011a.126 Production Release
//  HLS Date:       Wed Aug  8 00:52:07 PDT 2012
// 
//  Generated by:   jb914@EEWS104A-014
//  Generated date: Wed May 06 14:30:15 2015
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    green_tint_core
// ------------------------------------------------------------------


module green_tint_core (
  clk, en, arst_n, video_in_rsc_mgc_in_wire_d, video_out_rsc_mgc_out_stdreg_d, mouse_xy_rsc_mgc_in_wire_d
);
  input clk;
  input en;
  input arst_n;
  input [29:0] video_in_rsc_mgc_in_wire_d;
  output [29:0] video_out_rsc_mgc_out_stdreg_d;
  reg [29:0] video_out_rsc_mgc_out_stdreg_d;
  input [19:0] mouse_xy_rsc_mgc_in_wire_d;



  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : core
    // Interconnect Declarations
    reg [7:0] slc_mouse_xy_psp_sva;
    reg [29:0] io_read_video_in_rsc_d_cse_sva;
    reg [9:0] else_else_acc_psp_sva_sg1;
    reg [9:0] else_else_acc_1_psp_sva_sg1;

    begin : mainExit
      forever begin : main
        // C-Step 0 of Loop 'main'
        begin : waitLoop0Exit
          forever begin : waitLoop0
            @(posedge clk or negedge ( arst_n ));
            if ( ~ arst_n )
              disable mainExit;
            if ( en )
              disable waitLoop0Exit;
          end
        end
        // C-Step 1 of Loop 'main'
        slc_mouse_xy_psp_sva = mouse_xy_rsc_mgc_in_wire_d[8:1];
        io_read_video_in_rsc_d_cse_sva = video_in_rsc_mgc_in_wire_d;
        else_else_acc_psp_sva_sg1 = readslicef_11_10_1((conv_u2u_10_11({(io_read_video_in_rsc_d_cse_sva[29:21])
            , 1'b1}) + conv_s2u_10_11({1'b1 , (~ slc_mouse_xy_psp_sva) , 1'b1})));
        else_else_acc_1_psp_sva_sg1 = readslicef_11_10_1((conv_u2u_10_11({(io_read_video_in_rsc_d_cse_sva[9:1])
            , 1'b1}) + conv_s2u_10_11({1'b1 , (~ slc_mouse_xy_psp_sva) , 1'b1})));
        video_out_rsc_mgc_out_stdreg_d <= {(({(else_else_acc_psp_sva_sg1[8:0]) ,
            (readslicef_2_1_1((({(io_read_video_in_rsc_d_cse_sva[20]) , 1'b1}) +
            2'b11)))}) & (signext_10_1(~ (else_else_acc_psp_sva_sg1[9])))) , (io_read_video_in_rsc_d_cse_sva[19:10])
            , (({(else_else_acc_1_psp_sva_sg1[8:0]) , (readslicef_2_1_1((({(io_read_video_in_rsc_d_cse_sva[0])
            , 1'b1}) + 2'b11)))}) & (signext_10_1(~ (else_else_acc_1_psp_sva_sg1[9]))))};
      end
    end
    else_else_acc_1_psp_sva_sg1 = 10'b0;
    else_else_acc_psp_sva_sg1 = 10'b0;
    io_read_video_in_rsc_d_cse_sva = 30'b0;
    slc_mouse_xy_psp_sva = 8'b0;
    video_out_rsc_mgc_out_stdreg_d <= 30'b0;
  end


  function [9:0] readslicef_11_10_1;
    input [10:0] vector;
    reg [10:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_11_10_1 = tmp[9:0];
  end
  endfunction


  function [0:0] readslicef_2_1_1;
    input [1:0] vector;
    reg [1:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_2_1_1 = tmp[0:0];
  end
  endfunction


  function [9:0] signext_10_1;
    input [0:0] vector;
  begin
    signext_10_1= {{9{vector[0]}}, vector};
  end
  endfunction


  function  [10:0] conv_u2u_10_11 ;
    input [9:0]  vector ;
  begin
    conv_u2u_10_11 = {1'b0, vector};
  end
  endfunction


  function  [10:0] conv_s2u_10_11 ;
    input signed [9:0]  vector ;
  begin
    conv_s2u_10_11 = {vector[9], vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    green_tint
//  Generated from file(s):
//    3) $PROJECT_HOME/MouseTintGreen.c
// ------------------------------------------------------------------


module green_tint (
  video_in_rsc_z, video_out_rsc_z, mouse_xy_rsc_z, clk, en, arst_n
);
  input [29:0] video_in_rsc_z;
  output [29:0] video_out_rsc_z;
  input [19:0] mouse_xy_rsc_z;
  input clk;
  input en;
  input arst_n;


  // Interconnect Declarations
  wire [29:0] video_in_rsc_mgc_in_wire_d;
  wire [29:0] video_out_rsc_mgc_out_stdreg_d;
  wire [19:0] mouse_xy_rsc_mgc_in_wire_d;


  // Interconnect Declarations for Component Instantiations 
  mgc_in_wire #(.rscid(1),
  .width(30)) video_in_rsc_mgc_in_wire (
      .d(video_in_rsc_mgc_in_wire_d),
      .z(video_in_rsc_z)
    );
  mgc_out_stdreg #(.rscid(2),
  .width(30)) video_out_rsc_mgc_out_stdreg (
      .d(video_out_rsc_mgc_out_stdreg_d),
      .z(video_out_rsc_z)
    );
  mgc_in_wire #(.rscid(3),
  .width(20)) mouse_xy_rsc_mgc_in_wire (
      .d(mouse_xy_rsc_mgc_in_wire_d),
      .z(mouse_xy_rsc_z)
    );
  green_tint_core green_tint_core_inst (
      .clk(clk),
      .en(en),
      .arst_n(arst_n),
      .video_in_rsc_mgc_in_wire_d(video_in_rsc_mgc_in_wire_d),
      .video_out_rsc_mgc_out_stdreg_d(video_out_rsc_mgc_out_stdreg_d),
      .mouse_xy_rsc_mgc_in_wire_d(mouse_xy_rsc_mgc_in_wire_d)
    );
endmodule



