
# Loop constraints
directive set /edge_detect/core/core:rlp CSTEPS_FROM {{. == 0}}
directive set /edge_detect/core/core:rlp/main CSTEPS_FROM {{. == 3} {.. == 0}}

# IO operation constraints
directive set /edge_detect/core/core:rlp/main/FRAME:io_read(vin:rsc.d) CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:io_write(vout:rsc.d) CSTEPS_FROM {{.. == 2}}

# Real operation constraints
directive set /edge_detect/core/core:rlp/main/SHIFT:and CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#2 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#3 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#4 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#5 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#6 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#7 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#8 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#9 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#10 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#11 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#12 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#13 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#14 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#15 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#16 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#17 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#18 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#19 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#20 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#21 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#22 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#23 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#24 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#25 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:mux CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:mux#16 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:mux#17 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:mux#18 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:mux#19 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:mux#20 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax:if:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax:else:if:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax#1:if:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax#1:else:if:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax#2:if:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax#2:else:if:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax#3:if:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax#3:else:if:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax#4:if:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax#4:else:if:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax#5:if:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax#5:else:if:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax:mux1h CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax#1:mux1h CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax#6:if:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax#6:else:if:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax#4:mux1h CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax#5:mux1h CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax#7:if:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax#7:else:if:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax#2:mux1h CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax#3:mux1h CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax#8:if:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax#8:else:if:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax#7:mux1h CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax#8:mux1h CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/AbsAndMax#6:mux1h CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#12 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#11 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#14 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#13 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#15 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#16 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#17 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#18 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/acc#2 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#32 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#20 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#22 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#24 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#33 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#26 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#28 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#30 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#19 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#21 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#23 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#25 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#27 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#29 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#31 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:acc#6 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:or CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:or#3 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/ACC_GX:for:acc#13 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GX:for:acc#14 CSTEPS_FROM {{.. == 1}}
directive set {/edge_detect/core/core:rlp/main/regs.operator[]:mux} CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GX:for:mux CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GX:for:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GX:for:mux#15 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GX:for:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GX:for:rshift CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GX:for:mul#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GX:for:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GX:for:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GX:for:mux#16 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GX:for:mux#17 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GX:for:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GX:for:mux#18 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GX:for:mul#3 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GX:for:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GX:for:mux#19 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GX:for:mux#20 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GX:for:mul#6 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GX:for:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GX:for:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GY:for:acc#13 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GY:for:acc#15 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GY:for:acc#14 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GY:for:mux CSTEPS_FROM {{.. == 1}}
directive set {/edge_detect/core/core:rlp/main/regs.operator[]#3:mux} CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GY:for:mux#9 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GY:for:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GY:for:rshift CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GY:for:mul#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GY:for:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GY:for:mux#10 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GY:for:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GY:for:mux#11 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GY:for:mul#3 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GY:for:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GY:for:mux#12 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GY:for:mux#13 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GY:for:mul#6 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GY:for:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GY:for:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GX:for:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GY:for:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GX:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GY:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GX:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GY:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/and#18 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/and#19 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GX:and#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:if:else:else:else:mux CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#27 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#28 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#29 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#30 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#36 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#37 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#38 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#39 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#40 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#41 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#42 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#43 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#44 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#45 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#46 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#47 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#48 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#49 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#50 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#51 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#52 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#53 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#54 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#55 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#56 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#57 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#58 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#59 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#60 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#61 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#62 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#3 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#86 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#2 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#4 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC_GX:mux#67 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#106 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#107 CSTEPS_FROM {{.. == 1}}
