
# Loop constraints
directive set /sharpen1/core/core:rlp CSTEPS_FROM {{. == 0}}
directive set /sharpen1/core/core:rlp/main CSTEPS_FROM {{. == 2} {.. == 0}}

# IO operation constraints
directive set /sharpen1/core/core:rlp/main/FRAME:io_read(vin:rsc.d) CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:io_write(vout:rsc.d) CSTEPS_FROM {{.. == 1}}

# Real operation constraints
directive set /sharpen1/core/core:rlp/main/SHIFT:and CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:and#1 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:and#2 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:and#3 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:and#4 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:and#5 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:and#6 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:and#7 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:and#8 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:and#9 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:and#10 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:and#11 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#12 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#13 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC2:mux CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC2:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC2:mux#3 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC2:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC2:mux#4 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC2:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC2:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC2:acc CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/AbsAndMax:if:acc CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/AbsAndMax:else:if:acc CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/AbsAndMax#1:if:acc CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/AbsAndMax#1:else:if:acc CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/AbsAndMax#1:else:mux CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/AbsAndMax#2:if:acc CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/AbsAndMax#2:else:if:acc CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/AbsAndMax#2:mux1h CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/AbsAndMax:else:mux CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:or CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/AbsAndMax#1:and CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:or#3 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:or#4 CSTEPS_FROM {{.. == 1}}
directive set {/sharpen1/core/core:rlp/main/regs.operator[]:mux} CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if:acc#11 CSTEPS_FROM {{.. == 1}}
directive set {/sharpen1/core/core:rlp/main/regs.operator[]#1:mux} CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if:acc CSTEPS_FROM {{.. == 1}}
directive set {/sharpen1/core/core:rlp/main/regs.operator[]#2:mux} CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if:acc#12 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if#1:acc#32 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if#1:acc CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if#1:acc#33 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if#1:acc#34 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:mux#32 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if#1:acc#26 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if#1:acc#35 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:mux#1 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if#1:acc#27 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if#1:acc#36 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:mux#2 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if#1:acc#28 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if#1:acc#37 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if#1:acc#38 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if#1:acc#39 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:acc CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:and CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:if:else:else:else:mux CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:and#15 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#18 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#19 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#20 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#21 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#22 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#23 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#24 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux1h#2 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#26 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#27 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux1h#3 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#29 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#30 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux1h#4 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#32 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux1h CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#38 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux1h#1 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:mux#31 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#42 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#43 CSTEPS_FROM {{.. == 1}}
