
# Loop constraints
directive set /motion_blur/core/core:rlp CSTEPS_FROM {{. == 0}}
directive set /motion_blur/core/core:rlp/main CSTEPS_FROM {{. == 17} {.. == 0}}
directive set /motion_blur/core/core:rlp/main/SHIFT CSTEPS_FROM {{. == 1} {.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1 CSTEPS_FROM {{. == 1} {.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC2 CSTEPS_FROM {{. == 1} {.. == 1}}

# IO operation constraints
directive set /motion_blur/core/core:rlp/main/FRAME:io_read(vin:rsc.d) CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/FRAME:io_write(vout:rsc.d) CSTEPS_FROM {{.. == 16}}

# Real operation constraints
directive set /motion_blur/core/core:rlp/main/SHIFT/SHIFT:if:else:else:else:acc CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/SHIFT/SHIFT:if:else:else:else:mux CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/SHIFT/SHIFT:if:else:else:mux CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/SHIFT/SHIFT:if:else:else:mux#1 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/SHIFT/SHIFT:if:else:else:mux#2 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/SHIFT/SHIFT:if:else:else:mux#3 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/SHIFT/SHIFT:if:else:else:mux#4 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/SHIFT/SHIFT:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:if:acc CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:if:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:if:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:if#1:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:if#1:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:if#1:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:if#2:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:if#2:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:if#2:acc#8 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:if#3:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:if#3:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:if#3:acc#11 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:mux CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:mux#1 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:mux#2 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:mux#3 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:mux#4 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:mux#5 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:mux#6 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:mux#7 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:mux#8 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:mux#9 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:mux#10 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:mux#11 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:mux#12 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:mux#13 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:mux#14 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC1/ACC1:acc CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC2/ACC2:mux CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC2/ACC2:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC2/ACC2:mux#1 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC2/ACC2:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC2/ACC2:mux#2 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC2/ACC2:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC2/ACC2:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/ACC2/ACC2:acc CSTEPS_FROM {{.. == 1}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#8 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#7 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#10 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#9 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#11 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/acc CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:mul#3 CSTEPS_FROM {{.. == 13}}
directive set /motion_blur/core/core:rlp/main/FRAME:mul#2 CSTEPS_FROM {{.. == 10}}
directive set /motion_blur/core/core:rlp/main/FRAME:mul#1 CSTEPS_FROM {{.. == 7}}
directive set /motion_blur/core/core:rlp/main/FRAME:mul CSTEPS_FROM {{.. == 4}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#12 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#14 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#20 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#13 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#15 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#16 CSTEPS_FROM {{.. == 4}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#17 CSTEPS_FROM {{.. == 7}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#18 CSTEPS_FROM {{.. == 10}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#19 CSTEPS_FROM {{.. == 13}}
directive set /motion_blur/core/core:rlp/main/FRAME:mul#4 CSTEPS_FROM {{.. == 16}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#2 CSTEPS_FROM {{.. == 16}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#23 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#22 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#25 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#21 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#24 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#26 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/acc#2 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:mul#8 CSTEPS_FROM {{.. == 12}}
directive set /motion_blur/core/core:rlp/main/FRAME:mul#7 CSTEPS_FROM {{.. == 9}}
directive set /motion_blur/core/core:rlp/main/FRAME:mul#6 CSTEPS_FROM {{.. == 6}}
directive set /motion_blur/core/core:rlp/main/FRAME:mul#5 CSTEPS_FROM {{.. == 3}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#27 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#29 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#35 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#28 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#30 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#31 CSTEPS_FROM {{.. == 3}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#32 CSTEPS_FROM {{.. == 6}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#33 CSTEPS_FROM {{.. == 9}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#34 CSTEPS_FROM {{.. == 12}}
directive set /motion_blur/core/core:rlp/main/FRAME:mul#9 CSTEPS_FROM {{.. == 15}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#3 CSTEPS_FROM {{.. == 15}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#38 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#37 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#40 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#36 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#39 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#41 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/acc#4 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:mul#13 CSTEPS_FROM {{.. == 11}}
directive set /motion_blur/core/core:rlp/main/FRAME:mul#12 CSTEPS_FROM {{.. == 8}}
directive set /motion_blur/core/core:rlp/main/FRAME:mul#11 CSTEPS_FROM {{.. == 5}}
directive set /motion_blur/core/core:rlp/main/FRAME:mul#10 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#42 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#44 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#50 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#43 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#45 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#46 CSTEPS_FROM {{.. == 2}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#47 CSTEPS_FROM {{.. == 5}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#48 CSTEPS_FROM {{.. == 8}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#49 CSTEPS_FROM {{.. == 11}}
directive set /motion_blur/core/core:rlp/main/FRAME:mul#14 CSTEPS_FROM {{.. == 14}}
directive set /motion_blur/core/core:rlp/main/FRAME:acc#4 CSTEPS_FROM {{.. == 14}}
directive set /motion_blur/core/core:rlp/main/absmax:if:acc CSTEPS_FROM {{.. == 16}}
directive set /motion_blur/core/core:rlp/main/absmax:else:acc CSTEPS_FROM {{.. == 16}}
directive set /motion_blur/core/core:rlp/main/absmax:else:and CSTEPS_FROM {{.. == 16}}
directive set /motion_blur/core/core:rlp/main/absmax#1:if:acc CSTEPS_FROM {{.. == 14}}
directive set /motion_blur/core/core:rlp/main/absmax#1:else:acc CSTEPS_FROM {{.. == 14}}
directive set /motion_blur/core/core:rlp/main/absmax#1:else:and CSTEPS_FROM {{.. == 14}}
directive set /motion_blur/core/core:rlp/main/absmax#2:if:acc CSTEPS_FROM {{.. == 15}}
directive set /motion_blur/core/core:rlp/main/absmax#2:else:acc CSTEPS_FROM {{.. == 15}}
directive set /motion_blur/core/core:rlp/main/absmax#2:else:and CSTEPS_FROM {{.. == 15}}
directive set /motion_blur/core/core:rlp/main/absmax:or CSTEPS_FROM {{.. == 16}}
directive set /motion_blur/core/core:rlp/main/absmax#2:or CSTEPS_FROM {{.. == 15}}
directive set /motion_blur/core/core:rlp/main/absmax#1:or CSTEPS_FROM {{.. == 14}}
