
# Loop constraints
directive set /sharpen/core/core:rlp CSTEPS_FROM {{. == 0}}
directive set /sharpen/core/core:rlp/main CSTEPS_FROM {{. == 2} {.. == 0}}

# IO operation constraints
directive set /sharpen/core/core:rlp/main/FRAME:io_read(vin:rsc.d) CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/FRAME:io_write(vout:rsc.d) CSTEPS_FROM {{.. == 1}}

# Real operation constraints
directive set /sharpen/core/core:rlp/main/and#9 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:and CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:and#1 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:and#2 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:and#3 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:and#4 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:and#5 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:and#6 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:and#7 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:and#8 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:and#9 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:and#10 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:and#11 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:mux#12 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:mux#13 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC3:mux CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC3:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC3:mux#5 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC3:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC3:mux#6 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC3:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC3:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC3:acc CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/AbsAndMax:if:acc CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/AbsAndMax:else:if:acc CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/AbsAndMax#1:if:acc CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/AbsAndMax#1:else:if:acc CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/AbsAndMax#1:else:mux CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/AbsAndMax#2:if:acc CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/AbsAndMax#2:else:if:acc CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/AbsAndMax#2:mux1h CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/AbsAndMax:else:mux CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/FRAME:or CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/AbsAndMax#1:and CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/FRAME:or#3 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/FRAME:or#4 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/FRAME:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:for:acc#16 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:for:acc#17 CSTEPS_FROM {{.. == 1}}
directive set {/sharpen/core/core:rlp/main/regs.operator[]:mux} CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:for:mux CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:for:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:for:rshift CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:for:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:for:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:for:mux#15 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:for:and CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:for:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:for:acc#8 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:for:mux#16 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:for:mux#17 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:for:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:for:mux#18 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:for:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:for:and#1 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:for:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:for:mux#19 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:for:mux#20 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:for:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:for:and#2 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:for:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:for:acc#12 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:for:acc CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:acc CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:for:and#3 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:and#1 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:if:else:else:else:mux CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:and#16 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:and#17 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:mux#43 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC3:mux#4 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:mux#29 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:mux#55 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:mux#62 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:mux#21 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:mux#22 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:mux#23 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:mux#24 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:mux#25 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:mux#26 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:mux#27 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:mux#28 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:mux#29 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:mux#30 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:mux#31 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:mux#32 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:mux#33 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:mux#34 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:mux#35 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:mux1h CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:mux1h#2 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:mux#46 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:mux1h#1 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/ACC_GX:mux#33 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:mux#59 CSTEPS_FROM {{.. == 1}}
directive set /sharpen/core/core:rlp/main/SHIFT:mux#60 CSTEPS_FROM {{.. == 1}}
