
# Loop constraints
directive set /edge_detect/core/core:rlp CSTEPS_FROM {{. == 0}}
directive set /edge_detect/core/core:rlp/main CSTEPS_FROM {{. == 3} {.. == 0}}

# IO operation constraints
directive set /edge_detect/core/core:rlp/main/FRAME:io_read(vin:rsc.d) CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:io_write(vout:rsc.d) CSTEPS_FROM {{.. == 2}}

# Real operation constraints
directive set /edge_detect/core/core:rlp/main/SHIFT:and CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#2 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#3 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#4 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#5 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#6 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#7 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#8 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#9 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#10 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#11 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#12 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#13 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#14 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#15 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#16 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC4:mux CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC4:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC4:mux#8 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC4:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC4:mux#9 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC4:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC4:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC4:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/absmax:if:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/absmax:else:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/absmax:else:else:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/absmax#1:if:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/absmax#1:else:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/absmax#1:else:else:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/absmax#2:if:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/absmax#2:else:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/absmax#2:else:else:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/absmax#1:mux1h CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/absmax#2:mux1h CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/absmax:mux1h CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc#8 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc#11 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/acc#2 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc#25 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc#13 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc#15 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc#17 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc#26 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc#19 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc#21 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc#23 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc#12 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc#14 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc#16 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc#18 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc#20 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc#22 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc#24 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:avg:acc#1 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/absmax#3:if:acc CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/absmax#3:else:acc CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/absmax#3:else:else:acc CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/absmax#3:mux1h CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:or CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/FRAME:or#3 CSTEPS_FROM {{.. == 2}}
directive set /edge_detect/core/core:rlp/main/ACC2:mux CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC2:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC2:mux#23 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC2:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC2:mux#24 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC2:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC2:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if:acc#21 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if:acc#22 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if:acc#8 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if#1:acc#28 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if#1:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if#1:acc#29 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if#1:acc#23 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if#1:acc#24 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if#1:acc#25 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if#2:acc#21 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if#2:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if#2:acc#22 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if#2:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if#2:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:if#2:acc#8 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC2:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC3:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC2:and CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if:acc#23 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if:acc#24 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if:acc#8 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if#1:acc#28 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if#1:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if#1:acc#29 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if#1:acc#25 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if#1:acc#26 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if#1:acc#27 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if#2:acc#23 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if#2:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if#2:acc#24 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if#2:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if#2:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:if#2:acc#8 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:acc CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:and#5 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:and#6 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:if:else:else:else:mux CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:and#19 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#24 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#25 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#26 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#15 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#16 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#17 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#8 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#9 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#10 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#11 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#12 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#13 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#2 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#3 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#4 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#5 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#6 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#7 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#18 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#48 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#14 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux1h#1 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC2:mux#20 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:mux#28 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#54 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/ACC1:mux#29 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#55 CSTEPS_FROM {{.. == 1}}
directive set /edge_detect/core/core:rlp/main/SHIFT:mux#56 CSTEPS_FROM {{.. == 1}}
