
# Loop constraints
directive set /sharpen1/core/core:rlp CSTEPS_FROM {{. == 0}}
directive set /sharpen1/core/core:rlp/main CSTEPS_FROM {{. == 2} {.. == 0}}

# IO operation constraints
directive set /sharpen1/core/core:rlp/main/FRAME:io_read(vin:rsc.d) CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:io_write(vout:rsc.d) CSTEPS_FROM {{.. == 1}}

# Real operation constraints
directive set /sharpen1/core/core:rlp/main/SHIFT:and CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:and#1 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:and#2 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:and#3 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:and#4 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:and#5 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:and#6 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:and#7 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:and#8 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#9 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:and#9 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:and#10 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:and#11 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#13 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC2:mux CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC2:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC2:mux#5 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC2:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC2:mux#6 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC2:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC2:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC2:acc CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#8 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/acc CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#12 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#11 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#14 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#13 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#15 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/acc#2 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#22 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:mul#2 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:mul#3 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#23 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#16 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#17 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#18 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#19 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#20 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#21 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#25 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#24 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#27 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#26 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#28 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/acc#4 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#35 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:mul#4 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:mul#5 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#36 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#29 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#30 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#31 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#32 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#33 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#34 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:mul#1 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#44 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#37 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#38 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#39 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#40 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#41 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#43 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:mul CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#42 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:or CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/FRAME:or#3 CSTEPS_FROM {{.. == 1}}
directive set {/sharpen1/core/core:rlp/main/regs.operator[]:mux} CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if:acc#11 CSTEPS_FROM {{.. == 1}}
directive set {/sharpen1/core/core:rlp/main/regs.operator[]#1:mux} CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if:acc CSTEPS_FROM {{.. == 1}}
directive set {/sharpen1/core/core:rlp/main/regs.operator[]#2:mux} CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if:acc#12 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if#1:acc#32 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if#1:acc CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if#1:acc#33 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if#1:acc#34 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:mux#34 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if#1:acc#26 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if#1:acc#35 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:mux#1 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if#1:acc#27 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if#1:acc#36 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:mux#2 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if#1:acc#28 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if#1:acc#37 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if#1:acc#38 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:if#1:acc#39 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:acc CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:and CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:if:else:else:else:mux CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:and#15 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#21 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#22 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#23 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#24 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux1h#2 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#26 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#27 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux1h#3 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#29 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#30 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux1h#4 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#32 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#34 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#35 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#36 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux1h CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#40 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux1h#1 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/ACC1:mux#33 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#44 CSTEPS_FROM {{.. == 1}}
directive set /sharpen1/core/core:rlp/main/SHIFT:mux#45 CSTEPS_FROM {{.. == 1}}
